# Generated by Django 6.0 on 2025-12-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Maximum 200 characters', max_length=100),
        ),
    ]
