# Generated by Django 6.0 on 2025-12-23 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_tag_alter_post_title_post_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this bookmark')),
                ('collection', models.CharField(blank=True, help_text='Collection/folder name for organization', max_length=100)),
                ('post', models.ForeignKey(help_text='Post that was bookmarked', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='blog.post')),
                ('user', models.ForeignKey(help_text='User who bookmarked the post', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='blog_bookma_user_id_bd162a_idx'), models.Index(fields=['user', 'collection'], name='blog_bookma_user_id_7ccc3f_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of visitor', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('referrer', models.URLField(blank=True, help_text='URL the visitor came from', max_length=500)),
                ('session_id', models.CharField(blank=True, help_text='Session ID for tracking unique sessions', max_length=100)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Time spent on page in seconds')),
                ('post', models.ForeignKey(help_text='Post that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.post')),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed the post (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post View',
                'verbose_name_plural': 'Post Views',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', '-created_at'], name='blog_postvi_post_id_b73147_idx'), models.Index(fields=['user', '-created_at'], name='blog_postvi_user_id_25932d_idx'), models.Index(fields=['ip_address'], name='blog_postvi_ip_addr_e37efe_idx'), models.Index(fields=['session_id'], name='blog_postvi_session_ee247e_idx')],
            },
        ),
    ]
