# Generated by Django 6.0 on 2025-12-23 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, help_text='Short biography (max 500 chars)', max_length=500)),
                ('date_of_birth', models.DateField(blank=True, help_text='User birth date', null=True)),
                ('website', models.URLField(blank=True, help_text='Personal website URL')),
                ('github', models.CharField(blank=True, help_text='GitHub username', max_length=100)),
                ('twitter', models.CharField(blank=True, help_text='Twitter handle (without @)', max_length=100)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='User preferences stored as JSON')),
                ('posts_count', models.PositiveIntegerField(default=0, help_text='Cached count of user posts')),
                ('followers_count', models.PositiveIntegerField(default=0, help_text='Cached count of followers')),
                ('is_public', models.BooleanField(default=True, help_text='Is this profile visible to others?')),
                ('user', models.OneToOneField(help_text='User this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('comment', 'New Comment'), ('like', 'New Like'), ('mention', 'Mentioned You'), ('follow', 'New Follower'), ('system', 'System Notification')], default='info', help_text='Type of notification', max_length=20)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('link', models.URLField(blank=True, help_text='URL to navigate when notification is clicked')),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (e.g., "post", "comment")', max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Has user read this notification?')),
                ('read_at', models.DateTimeField(blank=True, help_text='When was this notification read?', null=True)),
                ('is_important', models.BooleanField(default=False, help_text='Is this an important notification?')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='users_notif_user_id_1be17e_idx'), models.Index(fields=['user', '-created_at'], name='users_notif_user_id_c37f16_idx'), models.Index(fields=['notification_type'], name='users_notif_notific_af6ddd_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('login', 'Logged In'), ('logout', 'Logged Out'), ('register', 'Registered'), ('password_change', 'Changed Password'), ('password_reset', 'Reset Password'), ('post_create', 'Created Post'), ('post_update', 'Updated Post'), ('post_delete', 'Deleted Post'), ('post_publish', 'Published Post'), ('comment_create', 'Created Comment'), ('comment_update', 'Updated Comment'), ('comment_delete', 'Deleted Comment'), ('profile_update', 'Updated Profile'), ('avatar_change', 'Changed Avatar'), ('follow', 'Followed User'), ('unfollow', 'Unfollowed User'), ('like', 'Liked Post'), ('unlike', 'Unliked Post'), ('admin_action', 'Admin Action'), ('view', 'Viewed Content'), ('download', 'Downloaded File'), ('other', 'Other Action')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('description', models.CharField(help_text='Brief description of the activity', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the activity (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from where action was performed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('object_type', models.CharField(blank=True, help_text='Type of object affected (e.g., "post", "comment")', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of affected object', null=True)),
                ('is_successful', models.BooleanField(default=True, help_text='Was the action successful?')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_usera_user_id_250303_idx'), models.Index(fields=['action_type', '-created_at'], name='users_usera_action__b1c302_idx'), models.Index(fields=['ip_address'], name='users_usera_ip_addr_20d9f6_idx')],
            },
        ),
    ]
