# Generated by Django 6.0.2 on 2026-02-13 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="When the forecast was generated."
                    ),
                ),
                ("forecast_hour", models.DateTimeField(help_text="The hour being forecasted.")),
                ("predicted_mw", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "actual_mw",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("confidence_lower", models.DecimalField(decimal_places=2, max_digits=10)),
                ("confidence_upper", models.DecimalField(decimal_places=2, max_digits=10)),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
            ],
            options={
                "verbose_name": "Demand Forecast",
                "verbose_name_plural": "Demand Forecasts",
                "ordering": ["-forecast_hour"],
            },
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Plant code, e.g. AQABA.", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_ar", models.CharField(blank=True, max_length=255)),
                (
                    "plant_type",
                    models.CharField(
                        choices=[
                            ("steam", "Steam Turbine"),
                            ("gas", "Gas Turbine"),
                            ("ccgt", "Combined Cycle Gas Turbine"),
                        ],
                        max_length=10,
                    ),
                ),
                ("fuel_type", models.CharField(blank=True, max_length=100)),
                ("capacity_mw", models.DecimalField(decimal_places=2, max_digits=8)),
                ("commissioned_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Under Maintenance"),
                            ("derated", "Derated"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("current_load_mw", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                (
                    "efficiency_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Plant",
                "verbose_name_plural": "Plants",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="HeatRateRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "heat_rate_btu_kwh",
                    models.DecimalField(
                        decimal_places=2, help_text="Heat rate in BTU/kWh.", max_digits=10
                    ),
                ),
                ("fuel_consumption_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("power_output_mw", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "ambient_temp_c",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heat_rate_records",
                        to="operations.plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Heat Rate Record",
                "verbose_name_plural": "Heat Rate Records",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EmissionsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "nox_ppm",
                    models.DecimalField(decimal_places=2, help_text="NOx in ppm.", max_digits=8),
                ),
                (
                    "co2_tonnes",
                    models.DecimalField(
                        decimal_places=2, help_text="CO2 in tonnes.", max_digits=10
                    ),
                ),
                (
                    "sox_ppm",
                    models.DecimalField(decimal_places=2, help_text="SOx in ppm.", max_digits=8),
                ),
                ("nox_limit", models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ("co2_limit", models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ("sox_limit", models.DecimalField(decimal_places=2, default=150, max_digits=8)),
                ("is_compliant", models.BooleanField(default=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emissions_records",
                        to="operations.plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emissions Record",
                "verbose_name_plural": "Emissions Records",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Turbine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "turbine_id",
                    models.CharField(help_text="Turbine identifier, e.g. A1.", max_length=10),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("capacity_mw", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Under Maintenance"),
                            ("trip", "Tripped"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("hours_since_maintenance", models.PositiveIntegerField(default=0)),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turbines",
                        to="operations.plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turbine",
                "verbose_name_plural": "Turbines",
                "ordering": ["plant", "turbine_id"],
                "unique_together": {("plant", "turbine_id")},
            },
        ),
        migrations.CreateModel(
            name="MaintenancePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("bearing", "Bearing Failure"),
                            ("blade", "Blade Degradation"),
                            ("seal", "Seal Leak"),
                            ("gearbox", "Gearbox Failure"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(help_text="Confidence score 0.0 to 1.0.")),
                ("predicted_failure_date", models.DateField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                ("recommended_action", models.TextField(blank=True)),
                ("recommended_action_ar", models.TextField(blank=True)),
                ("is_acknowledged", models.BooleanField(default=False)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turbine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_predictions",
                        to="operations.turbine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Prediction",
                "verbose_name_plural": "Maintenance Predictions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "reading_type",
                    models.CharField(
                        choices=[
                            ("vibration", "Vibration (mm/s)"),
                            ("temperature", "Temperature (°C)"),
                            ("pressure", "Pressure (bar)"),
                            ("rpm", "RPM"),
                            ("exhaust_temp", "Exhaust Temperature (°C)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=12)),
                ("unit", models.CharField(max_length=20)),
                ("is_anomaly", models.BooleanField(default=False)),
                ("anomaly_score", models.FloatField(blank=True, null=True)),
                (
                    "turbine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_readings",
                        to="operations.turbine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor Reading",
                "verbose_name_plural": "Sensor Readings",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["turbine", "reading_type", "timestamp"],
                        name="operations__turbine_2d0962_idx",
                    )
                ],
            },
        ),
    ]
