# Generated by Django 6.0.2 on 2026-02-13 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("billing_period_start", models.DateField()),
                ("billing_period_end", models.DateField()),
                ("total_amount_fils", models.PositiveIntegerField(default=0)),
                ("total_kwh", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("peak_kwh", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("off_peak_kwh", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("previous_reading", models.PositiveIntegerField(default=0)),
                ("current_reading", models.PositiveIntegerField(default=0)),
                ("due_date", models.DateField()),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "scanned_image",
                    models.ImageField(blank=True, null=True, upload_to="bills/scans/"),
                ),
                ("raw_ocr_data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
                "ordering": ["-billing_period_end"],
            },
        ),
        migrations.CreateModel(
            name="ConversationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "platform",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("web", "Web"), ("api", "API")],
                        default="whatsapp",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("context", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Conversation Session",
                "verbose_name_plural": "Conversation Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscriber_number", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name_ar", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("address_ar", models.TextField(blank=True)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("meter_number", models.CharField(blank=True, max_length=50)),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                        ],
                        default="residential",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TariffPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("name_ar", models.CharField(blank=True, max_length=50)),
                ("start_hour", models.PositiveSmallIntegerField(help_text="Hour of day (0-23).")),
                ("end_hour", models.PositiveSmallIntegerField(help_text="Hour of day (0-23).")),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Rate multiplier for this period.",
                        max_digits=4,
                    ),
                ),
                ("is_peak", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Tariff Period",
                "verbose_name_plural": "Tariff Periods",
                "ordering": ["start_hour"],
            },
        ),
        migrations.CreateModel(
            name="BillLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                ("description_ar", models.CharField(blank=True, max_length=255)),
                ("amount_fils", models.IntegerField(default=0)),
                ("kwh", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("tariff_tier", models.CharField(blank=True, max_length=50)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="consumer.bill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill Line Item",
                "verbose_name_plural": "Bill Line Items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[("text", "Text"), ("voice", "Voice"), ("image", "Image")],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("audio_url", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("cost_usd", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ("processing_time_ms", models.PositiveIntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="consumer.conversationsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="consumer.subscription",
            ),
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "complaint_type",
                    models.CharField(
                        choices=[
                            ("outage", "Power Outage"),
                            ("billing", "Billing Issue"),
                            ("meter", "Meter Problem"),
                            ("voltage", "Voltage Issue"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("description_ar", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("jepco_reference", models.CharField(blank=True, max_length=100)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="consumer.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint",
                "verbose_name_plural": "Complaints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bill",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="consumer.subscription",
            ),
        ),
        migrations.CreateModel(
            name="TariffTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tier_number", models.PositiveSmallIntegerField()),
                ("min_kwh", models.PositiveIntegerField()),
                ("max_kwh", models.PositiveIntegerField(help_text="Use 999999 for unlimited.")),
                ("rate_fils", models.PositiveIntegerField(help_text="Rate in fils per kWh.")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tariff Tier",
                "verbose_name_plural": "Tariff Tiers",
                "ordering": ["sector", "tier_number"],
                "unique_together": {("sector", "tier_number")},
            },
        ),
    ]
