# Generated by Django 6.0.2 on 2026-02-14 08:29

import apps.consumer.models.conversation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationsession",
            name="session_key",
            field=models.CharField(
                db_index=True,
                default=apps.consumer.models.conversation.generate_session_key,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
