# Generated by Django 6.0.2 on 2026-02-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_name", models.CharField(max_length=100)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("local", "Local"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cost_usd", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("vision", "Vision"),
                            ("stt", "Speech-to-Text"),
                            ("tts", "Text-to-Speech"),
                            ("rag", "RAG"),
                            ("chat", "Chat"),
                            ("crew", "Crew"),
                        ],
                        max_length=20,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AI Log",
                "verbose_name_plural": "AI Logs",
                "db_table": "ai_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
